name: Build for Android ARMv7 (API 14+)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-android-armv7:
    runs-on: ubuntu-latest

    env:
      ANDROID_API: 14
      ARCH: armeabi-v7a

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nmeum/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Set up Build Directory
        run: mkdir -p android-arm32-build

      - name: Build Example App for Android ARMv7
        working-directory: android-arm32-build
        run: |
          export CC=armv7a-linux-androideabi${ANDROID_API}-clang
          export CXX=armv7a-linux-androideabi${ANDROID_API}-clang++
          echo '#include <stdio.h>
          int main() { printf("Hello from Android ARM32!\\n"); return 0; }' > hello.c
          
          $CC hello.c -o hello_arm32

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-arm32-binary
          path: android-arm32-build/hello_arm32
